-- 0003_seed_tickers.sql — base PSX listings (refreshed live by /api/cron/refresh)
insert into public.tickers (symbol, company_name, sector, listed_in, is_active) values
  ('OGDC', 'Oil & Gas Development Co.', 'Oil & Gas Exploration', 'REG', true),
  ('PPL', 'Pakistan Petroleum Ltd.', 'Oil & Gas Exploration', 'REG', true),
  ('POL', 'Pakistan Oilfields Ltd.', 'Oil & Gas Exploration', 'REG', true),
  ('MARI', 'Mari Petroleum Co.', 'Oil & Gas Exploration', 'REG', true),
  ('PSO', 'Pakistan State Oil Co.', 'Oil & Gas Marketing', 'REG', true),
  ('APL', 'Attock Petroleum Ltd.', 'Oil & Gas Marketing', 'REG', true),
  ('HASCOL', 'Hascol Petroleum Ltd.', 'Oil & Gas Marketing', 'REG', true),
  ('LUCK', 'Lucky Cement Ltd.', 'Cement', 'REG', true),
  ('DGKC', 'D.G. Khan Cement Co.', 'Cement', 'REG', true),
  ('MLCF', 'Maple Leaf Cement Factory', 'Cement', 'REG', true),
  ('FCCL', 'Fauji Cement Co.', 'Cement', 'REG', true),
  ('CHCC', 'Cherat Cement Co.', 'Cement', 'REG', true),
  ('ENGRO', 'Engro Corporation Ltd.', 'Fertilizer', 'REG', true),
  ('FFC', 'Fauji Fertilizer Co.', 'Fertilizer', 'REG', true),
  ('EFERT', 'Engro Fertilizers Ltd.', 'Fertilizer', 'REG', true),
  ('FFBL', 'Fauji Fertilizer Bin Qasim', 'Fertilizer', 'REG', true),
  ('HBL', 'Habib Bank Ltd.', 'Commercial Banks', 'REG', true),
  ('UBL', 'United Bank Ltd.', 'Commercial Banks', 'REG', true),
  ('MCB', 'MCB Bank Ltd.', 'Commercial Banks', 'REG', true),
  ('BAHL', 'Bank Al Habib Ltd.', 'Commercial Banks', 'REG', true),
  ('MEBL', 'Meezan Bank Ltd.', 'Commercial Banks', 'REG', true),
  ('BAFL', 'Bank Alfalah Ltd.', 'Commercial Banks', 'REG', true),
  ('ABL', 'Allied Bank Ltd.', 'Commercial Banks', 'REG', true),
  ('NBP', 'National Bank of Pakistan', 'Commercial Banks', 'REG', true),
  ('ENGROH', 'Engro Holdings Ltd.', 'Holding Companies', 'REG', true),
  ('PSEL', 'Pak Suzuki Motor Co.', 'Automobile Assembler', 'REG', true),
  ('INDU', 'Indus Motor Company Ltd.', 'Automobile Assembler', 'REG', true),
  ('HCAR', 'Honda Atlas Cars (Pak) Ltd.', 'Automobile Assembler', 'REG', true),
  ('MTL', 'Millat Tractors Ltd.', 'Automobile Assembler', 'REG', true),
  ('SYS', 'Systems Ltd.', 'Technology & Communication', 'REG', true),
  ('TRG', 'TRG Pakistan Ltd.', 'Technology & Communication', 'REG', true),
  ('AVN', 'Avanceon Ltd.', 'Technology & Communication', 'REG', true),
  ('NETSOL', 'NetSol Technologies Ltd.', 'Technology & Communication', 'REG', true),
  ('PTC', 'Pakistan Telecommunication Co.', 'Technology & Communication', 'REG', true),
  ('SEARL', 'The Searle Company Ltd.', 'Pharmaceuticals', 'REG', true),
  ('AGP', 'AGP Ltd.', 'Pharmaceuticals', 'REG', true),
  ('HINOON', 'Highnoon Laboratories Ltd.', 'Pharmaceuticals', 'REG', true),
  ('NESTLE', 'Nestle Pakistan Ltd.', 'Food & Personal Care', 'REG', true),
  ('NATF', 'National Foods Ltd.', 'Food & Personal Care', 'REG', true),
  ('UNITY', 'Unity Foods Ltd.', 'Food & Personal Care', 'REG', true),
  ('HUBC', 'Hub Power Company Ltd.', 'Power Generation & Distribution', 'REG', true),
  ('KAPCO', 'Kot Addu Power Co.', 'Power Generation & Distribution', 'REG', true),
  ('KEL', 'K-Electric Ltd.', 'Power Generation & Distribution', 'REG', true),
  ('ISL', 'International Steels Ltd.', 'Engineering', 'REG', true),
  ('ASTL', 'Amreli Steels Ltd.', 'Engineering', 'REG', true),
  ('PIOC', 'Pioneer Cement Ltd.', 'Cement', 'REG', true)
on conflict (symbol) do update set
  company_name = excluded.company_name,
  sector = excluded.sector,
  is_active = excluded.is_active,
  updated_at = now();
